USE [master]
GO
/****** Object:  Database [MJEM]    Script Date: 16-05-2020 23:49:16 ******/
CREATE DATABASE [MJEM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MJEM', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MJEM.mdf' , SIZE = 6336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MJEM_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MJEM_log.ldf' , SIZE = 2880KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MJEM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MJEM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MJEM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MJEM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MJEM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MJEM] SET ARITHABORT OFF 
GO
ALTER DATABASE [MJEM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MJEM] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [MJEM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MJEM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MJEM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MJEM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MJEM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MJEM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MJEM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MJEM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MJEM] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MJEM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MJEM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MJEM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MJEM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MJEM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MJEM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MJEM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MJEM] SET RECOVERY FULL 
GO
ALTER DATABASE [MJEM] SET  MULTI_USER 
GO
ALTER DATABASE [MJEM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MJEM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MJEM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MJEM] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [MJEM]
GO
