//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersMst
    {
        public CustomersMst()
        {
            this.JobSheetTxns = new HashSet<JobSheetTxn>();
            this.JobSheetTxns1 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns2 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns3 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns4 = new HashSet<JobSheetTxn>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string CustomerAddress { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<JobSheetTxn> JobSheetTxns { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns1 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns2 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns3 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns4 { get; set; }
    }
}
