//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplyoeeMst
    {
        public EmplyoeeMst()
        {
            this.JobSheetTxnDets = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets1 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets2 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets3 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets4 = new HashSet<JobSheetTxnDet>();
        }
    
        public int EmplyoeeId { get; set; }
        public string EmplyoeeName { get; set; }
        public string MobileNumber { get; set; }
        public string GovtId { get; set; }
        public string Address { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets1 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets2 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets3 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets4 { get; set; }
    }
}
