//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSheetTxn
    {
        public JobSheetTxn()
        {
            this.JobSheetTxnDets = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets1 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets2 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets3 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets4 = new HashSet<JobSheetTxnDet>();
        }
    
        public int JobSheetTxnId { get; set; }
        public int CustomerId { get; set; }
        public int LocationId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CustomersMst CustomersMst { get; set; }
        public virtual CustomersMst CustomersMst1 { get; set; }
        public virtual CustomersMst CustomersMst2 { get; set; }
        public virtual CustomersMst CustomersMst3 { get; set; }
        public virtual CustomersMst CustomersMst4 { get; set; }
        public virtual LocationMst LocationMst { get; set; }
        public virtual LocationMst LocationMst1 { get; set; }
        public virtual LocationMst LocationMst2 { get; set; }
        public virtual LocationMst LocationMst3 { get; set; }
        public virtual LocationMst LocationMst4 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets1 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets2 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets3 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets4 { get; set; }
    }
}
