//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSheetTxnDet
    {
        public int JobTxnSheetDetId { get; set; }
        public int JobSheetTxnId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int VechileId { get; set; }
        public Nullable<int> RunningHours { get; set; }
        public int EmplyoeeId { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> DriverBeta { get; set; }
        public int DieselFrom { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> DieselLtr { get; set; }
        public Nullable<decimal> DieselRate { get; set; }
    
        public virtual EmplyoeeMst EmplyoeeMst { get; set; }
        public virtual EmplyoeeMst EmplyoeeMst1 { get; set; }
        public virtual EmplyoeeMst EmplyoeeMst2 { get; set; }
        public virtual EmplyoeeMst EmplyoeeMst3 { get; set; }
        public virtual EmplyoeeMst EmplyoeeMst4 { get; set; }
        public virtual JobSheetTxn JobSheetTxn { get; set; }
        public virtual JobSheetTxn JobSheetTxn1 { get; set; }
        public virtual JobSheetTxn JobSheetTxn2 { get; set; }
        public virtual JobSheetTxn JobSheetTxn3 { get; set; }
        public virtual JobSheetTxn JobSheetTxn4 { get; set; }
        public virtual MJEMSysLov MJEMSysLov { get; set; }
        public virtual MJEMSysLov MJEMSysLov1 { get; set; }
        public virtual MJEMSysLov MJEMSysLov2 { get; set; }
        public virtual MJEMSysLov MJEMSysLov3 { get; set; }
        public virtual MJEMSysLov MJEMSysLov4 { get; set; }
        public virtual VechileMst VechileMst { get; set; }
        public virtual VechileMst VechileMst1 { get; set; }
        public virtual VechileMst VechileMst2 { get; set; }
        public virtual VechileMst VechileMst3 { get; set; }
        public virtual VechileMst VechileMst4 { get; set; }
    }
}
