//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMst
    {
        public LocationMst()
        {
            this.JobSheetTxns = new HashSet<JobSheetTxn>();
            this.JobSheetTxns1 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns2 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns3 = new HashSet<JobSheetTxn>();
            this.JobSheetTxns4 = new HashSet<JobSheetTxn>();
            this.LocationMst1 = new HashSet<LocationMst>();
            this.LocationMst11 = new HashSet<LocationMst>();
            this.LocationMst12 = new HashSet<LocationMst>();
            this.LocationMst13 = new HashSet<LocationMst>();
            this.LocationMst14 = new HashSet<LocationMst>();
        }
    
        public int LocationId { get; set; }
        public Nullable<int> ParentLocationId { get; set; }
        public string LocationName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<JobSheetTxn> JobSheetTxns { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns1 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns2 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns3 { get; set; }
        public virtual ICollection<JobSheetTxn> JobSheetTxns4 { get; set; }
        public virtual ICollection<LocationMst> LocationMst1 { get; set; }
        public virtual LocationMst LocationMst2 { get; set; }
        public virtual ICollection<LocationMst> LocationMst11 { get; set; }
        public virtual LocationMst LocationMst3 { get; set; }
        public virtual ICollection<LocationMst> LocationMst12 { get; set; }
        public virtual LocationMst LocationMst4 { get; set; }
        public virtual ICollection<LocationMst> LocationMst13 { get; set; }
        public virtual LocationMst LocationMst5 { get; set; }
        public virtual ICollection<LocationMst> LocationMst14 { get; set; }
        public virtual LocationMst LocationMst6 { get; set; }
    }
}
