//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintananceTxn
    {
        public int MaintananceTxnId { get; set; }
        public int MaintananceType { get; set; }
        public int ServiceType { get; set; }
        public int VechileId { get; set; }
        public Nullable<decimal> MaintanceCost { get; set; }
        public Nullable<System.DateTime> MaintananceDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MJEMSysLov MJEMSysLov { get; set; }
        public virtual MJEMSysLov MJEMSysLov1 { get; set; }
        public virtual MJEMSysLov MJEMSysLov2 { get; set; }
        public virtual MJEMSysLov MJEMSysLov3 { get; set; }
        public virtual MJEMSysLov MJEMSysLov4 { get; set; }
        public virtual MJEMSysLov MJEMSysLov5 { get; set; }
        public virtual MJEMSysLov MJEMSysLov6 { get; set; }
        public virtual MJEMSysLov MJEMSysLov7 { get; set; }
        public virtual MJEMSysLov MJEMSysLov8 { get; set; }
        public virtual MJEMSysLov MJEMSysLov9 { get; set; }
        public virtual VechileMst VechileMst { get; set; }
        public virtual VechileMst VechileMst1 { get; set; }
        public virtual VechileMst VechileMst2 { get; set; }
        public virtual VechileMst VechileMst3 { get; set; }
        public virtual VechileMst VechileMst4 { get; set; }
    }
}
