//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MJEMEntities : DbContext
    {
        public MJEMEntities()
            : base("name=MJEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CustomersMst> CustomersMsts { get; set; }
        public DbSet<EmplyoeeMst> EmplyoeeMsts { get; set; }
        public DbSet<JobSheetTxn> JobSheetTxns { get; set; }
        public DbSet<LocationMst> LocationMsts { get; set; }
        public DbSet<MaintananceTxn> MaintananceTxns { get; set; }
        public DbSet<MJEMSysLov> MJEMSysLovs { get; set; }
        public DbSet<SparePartsMst> SparePartsMsts { get; set; }
        public DbSet<VechileMst> VechileMsts { get; set; }
        public DbSet<JobSheetTxnDet> JobSheetTxnDets { get; set; }
    }
}
