//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MJEMSysLov
    {
        public MJEMSysLov()
        {
            this.MaintananceTxns = new HashSet<MaintananceTxn>();
            this.MaintananceTxns1 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns2 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns3 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns4 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns5 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns6 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns7 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns8 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns9 = new HashSet<MaintananceTxn>();
            this.MJEMSysLov1 = new HashSet<MJEMSysLov>();
            this.MJEMSysLov11 = new HashSet<MJEMSysLov>();
            this.MJEMSysLov12 = new HashSet<MJEMSysLov>();
            this.MJEMSysLov13 = new HashSet<MJEMSysLov>();
            this.MJEMSysLov14 = new HashSet<MJEMSysLov>();
            this.SparePartsMsts = new HashSet<SparePartsMst>();
            this.SparePartsMsts1 = new HashSet<SparePartsMst>();
            this.SparePartsMsts2 = new HashSet<SparePartsMst>();
            this.SparePartsMsts3 = new HashSet<SparePartsMst>();
            this.SparePartsMsts4 = new HashSet<SparePartsMst>();
            this.VechileMsts = new HashSet<VechileMst>();
            this.VechileMsts1 = new HashSet<VechileMst>();
            this.VechileMsts2 = new HashSet<VechileMst>();
            this.VechileMsts3 = new HashSet<VechileMst>();
            this.VechileMsts4 = new HashSet<VechileMst>();
            this.JobSheetTxnDets = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets1 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets2 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets3 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets4 = new HashSet<JobSheetTxnDet>();
        }
    
        public int LovId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ScreenName { get; set; }
        public string FieldName { get; set; }
        public string LovKey { get; set; }
        public string FieldCode { get; set; }
        public string FieldValue { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MaintananceTxn> MaintananceTxns { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns1 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns2 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns3 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns4 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns5 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns6 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns7 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns8 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns9 { get; set; }
        public virtual ICollection<MJEMSysLov> MJEMSysLov1 { get; set; }
        public virtual MJEMSysLov MJEMSysLov2 { get; set; }
        public virtual ICollection<MJEMSysLov> MJEMSysLov11 { get; set; }
        public virtual MJEMSysLov MJEMSysLov3 { get; set; }
        public virtual ICollection<MJEMSysLov> MJEMSysLov12 { get; set; }
        public virtual MJEMSysLov MJEMSysLov4 { get; set; }
        public virtual ICollection<MJEMSysLov> MJEMSysLov13 { get; set; }
        public virtual MJEMSysLov MJEMSysLov5 { get; set; }
        public virtual ICollection<MJEMSysLov> MJEMSysLov14 { get; set; }
        public virtual MJEMSysLov MJEMSysLov6 { get; set; }
        public virtual ICollection<SparePartsMst> SparePartsMsts { get; set; }
        public virtual ICollection<SparePartsMst> SparePartsMsts1 { get; set; }
        public virtual ICollection<SparePartsMst> SparePartsMsts2 { get; set; }
        public virtual ICollection<SparePartsMst> SparePartsMsts3 { get; set; }
        public virtual ICollection<SparePartsMst> SparePartsMsts4 { get; set; }
        public virtual ICollection<VechileMst> VechileMsts { get; set; }
        public virtual ICollection<VechileMst> VechileMsts1 { get; set; }
        public virtual ICollection<VechileMst> VechileMsts2 { get; set; }
        public virtual ICollection<VechileMst> VechileMsts3 { get; set; }
        public virtual ICollection<VechileMst> VechileMsts4 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets1 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets2 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets3 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets4 { get; set; }
    }
}
