//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsMst
    {
        public int SparePartId { get; set; }
        public Nullable<int> AvilableQuantity { get; set; }
        public Nullable<int> SpartPartType { get; set; }
        public string SpartPartName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MJEMSysLov MJEMSysLov { get; set; }
        public virtual MJEMSysLov MJEMSysLov1 { get; set; }
        public virtual MJEMSysLov MJEMSysLov2 { get; set; }
        public virtual MJEMSysLov MJEMSysLov3 { get; set; }
        public virtual MJEMSysLov MJEMSysLov4 { get; set; }
    }
}
