//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSAT.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VechileMst
    {
        public VechileMst()
        {
            this.MaintananceTxns = new HashSet<MaintananceTxn>();
            this.MaintananceTxns1 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns2 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns3 = new HashSet<MaintananceTxn>();
            this.MaintananceTxns4 = new HashSet<MaintananceTxn>();
            this.JobSheetTxnDets = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets1 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets2 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets3 = new HashSet<JobSheetTxnDet>();
            this.JobSheetTxnDets4 = new HashSet<JobSheetTxnDet>();
        }
    
        public int VechileId { get; set; }
        public Nullable<int> VehcileType { get; set; }
        public string VechileNumber { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MaintananceTxn> MaintananceTxns { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns1 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns2 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns3 { get; set; }
        public virtual ICollection<MaintananceTxn> MaintananceTxns4 { get; set; }
        public virtual MJEMSysLov MJEMSysLov { get; set; }
        public virtual MJEMSysLov MJEMSysLov1 { get; set; }
        public virtual MJEMSysLov MJEMSysLov2 { get; set; }
        public virtual MJEMSysLov MJEMSysLov3 { get; set; }
        public virtual MJEMSysLov MJEMSysLov4 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets1 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets2 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets3 { get; set; }
        public virtual ICollection<JobSheetTxnDet> JobSheetTxnDets4 { get; set; }
    }
}
